export default {
  compSearch: '', compFilterSeller: '', compFilterCat: '', compTab: 'overview',
  compData: {
    meta: { scrapedAt: '2026-05-12', totalProducts: 303, totalSellers: 19, totalCategories: 121, priceRange: { min: 9.99, max: 275.95, avg: 67.05 } },
    sellers: [
      { name: 'adidas ES', products: 93, avg: 64.79, min: 14.99, max: 185.82, cats: ['Balón Fútbol','Botas Fútbol Tacos','Zapatillas Baloncesto','Zapatillas Running','Zapatillas Trekking'] },
      { name: 'Sprinter', products: 92, avg: 80.51, min: 9.99, max: 234.99, cats: ['Botas fútbol tacos','Zapatillas running','Zapatillas casual','Zapatillas montaña','Zapatillas fitness'] },
      { name: 'Sports Sellers ES', products: 80, avg: 55.41, min: 15.07, max: 149.99, cats: ['Zapatillas Baloncesto','Zapatillas Trekking','Zapatillas Running','Camisetas Fútbol','Zapatillas Padel'] },
      { name: 'PadelPROShop', products: 9, avg: 69.95, min: 35.95, max: 189, cats: ['Pala Pádel','Zapatillas Padel'] },
      { name: 'AVENDA', products: 4, avg: 54.20, min: 28.80, max: 72.70, cats: ['Balón Fútbol','Zapatillas Padel'] },
      { name: 'Padel Cañaveral', products: 4, avg: 160.31, min: 44.73, max: 275.95, cats: ['Pala Pádel','Zapatillas Pádel'] },
      { name: 'AREA ZERO', products: 3, avg: 25.32, min: 22.99, max: 27.99, cats: ['Bandolera','Bolsa','Riñonera'] },
      { name: 'Imagina Sport', products: 3, avg: 38.99, min: 17.99, max: 54.99, cats: ['Mallas','Mochila'] },
      { name: 'Stateside', products: 3, avg: 67.91, min: 39.99, max: 101.15, cats: ['Zapatillas Padel','Zapatillas montaña','Zapatillas running'] },
      { name: 'JOMA', products: 2, avg: 83.49, min: 34.99, max: 131.99, cats: ['Zapatillas Fútbol Sala','Zapatillas Tenis'] },
      { name: 'TIENDA PADELPOINT', products: 2, avg: 48.45, min: 31.96, max: 64.95, cats: ['Zapatillas Pádel','Zapatillas Tenis'] },
      { name: 'Deporvillage', products: 1, avg: 31.95, min: 31.95, max: 31.95, cats: ['Forro Polar'] },
      { name: 'Factory Sport', products: 1, avg: 24.97, min: 24.97, max: 24.97, cats: ['Balón Fútbol'] },
      { name: 'ALONSPORT', products: 1, avg: 82.00, min: 82, max: 82, cats: ['Zapatillas Pádel'] },
      { name: 'Calzados Retos', products: 1, avg: 19.99, min: 19.99, max: 19.99, cats: ['Zapatillas Trekking'] },
      { name: 'Base Central Lab', products: 1, avg: 60.00, min: 60, max: 60, cats: ['Zapatillas running'] },
      { name: 'Vanessa Calzados', products: 1, avg: 17.99, min: 17.99, max: 17.99, cats: ['Zapatillas Niña'] },
      { name: 'Todo en Deporte', products: 1, avg: 32.74, min: 32.74, max: 32.74, cats: ['Botas Fútbol Sala'] },
      { name: 'Zona indoor', products: 1, avg: 34.99, min: 34.99, max: 34.99, cats: ['Zapatillas Baloncesto'] }
    ],
    categories: [
      { name: 'Zapatillas running', count: 28, avg: 98.11, min: 49.99, max: 149.99, sellers: ['Sprinter','Sports Sellers ES','adidas ES','Base Central Lab'] },
      { name: 'Zapatillas Baloncesto', count: 16, avg: 74.92, min: 34.99, max: 109.99, sellers: ['Sports Sellers ES','adidas ES','Zona indoor'] },
      { name: 'Zapatillas casual', count: 14, avg: 57.78, min: 32.99, max: 89.99, sellers: ['Sprinter'] },
      { name: 'Botas fútbol tacos', count: 13, avg: 97.68, min: 49.99, max: 234.99, sellers: ['Sprinter','adidas ES'] },
      { name: 'Zapatillas Trekking', count: 13, avg: 83.89, min: 19.99, max: 149.99, sellers: ['Sports Sellers ES','adidas ES','Calzados Retos'] },
      { name: 'Botas fútbol sala', count: 12, avg: 49.16, min: 24.99, max: 84.99, sellers: ['Sprinter'] },
      { name: 'Zapatillas montaña', count: 9, avg: 83.09, min: 39.99, max: 119.99, sellers: ['Sprinter','Stateside'] },
      { name: 'Balón Fútbol', count: 8, avg: 28.81, min: 24.97, max: 34.42, sellers: ['adidas ES','Sports Sellers ES','AVENDA','Factory Sport'] },
      { name: 'Zapatillas fitness', count: 8, avg: 97.21, min: 59.99, max: 119.99, sellers: ['Sprinter','Sports Sellers ES'] },
      { name: 'Botas Fútbol Tacos Jr', count: 6, avg: 88.32, min: 59.99, max: 129.99, sellers: ['Sprinter','adidas ES'] },
      { name: 'Zapatillas Trail', count: 5, avg: 77.52, min: 54.99, max: 102.65, sellers: ['Sports Sellers ES','adidas ES'] },
      { name: 'Zapatillas Pádel', count: 4, avg: 80.44, min: 31.96, max: 137.18, sellers: ['ALONSPORT','Padel Cañaveral','Sports Sellers ES','TIENDA PADELPOINT'] },
      { name: 'Sudadera Mujer', count: 4, avg: 49.99, min: 39.99, max: 74.99, sellers: ['Sports Sellers ES','adidas ES'] },
      { name: 'Camiseta Fútbol', count: 6, avg: 55.26, min: 26.99, max: 99.99, sellers: ['Sports Sellers ES','adidas ES'] },
      { name: 'Mochila', count: 3, avg: 38.45, min: 29.99, max: 44.99, sellers: ['Sports Sellers ES','adidas ES'] },
      { name: 'Zapatillas Tenis', count: 3, avg: 51.64, min: 39.99, max: 64.95, sellers: ['PadelPROShop','Sports Sellers ES','TIENDA PADELPOINT'] }
    ],
    products: [
      { n:'adidas Metalbone 26', p:275.95, op:0, b:'adidas', s:'Padel Cañaveral', c:'Pala Pádel' },
      { n:'adidas Cross It Light', p:249.95, op:0, b:'adidas', s:'Padel Cañaveral', c:'Pala Pádel Mujer' },
      { n:'adidas F50 Elite Fg Lamine Yamal', p:234.99, op:299.76, b:'adidas', s:'Sprinter', c:'Botas fútbol tacos' },
      { n:'Bullpadel Pack Vertex 04', p:189, op:0, b:'Bullpadel', s:'PadelPROShop', c:'Pala Pádel' },
      { n:'adidas Predator Elite Ft Fg', p:185.82, op:279.99, b:'adidas', s:'adidas ES', c:'Botas Fútbol Tacos' },
      { n:'adidas Predator Elite Ft Fg', p:179.99, op:279.99, b:'adidas', s:'Sprinter', c:'Botas fútbol tacos' },
      { n:'1ª Camiseta Real Madrid 25/26', p:149.99, op:0, b:'Real Madrid', s:'adidas ES', c:'Equipación' },
      { n:'adidas Adizero Evo Sl', p:149.99, op:0, b:'adidas', s:'Sprinter', c:'Zapatillas running' },
      { n:'La Sportiva Spire Gtx', p:149.99, op:227.80, b:'La Sportiva', s:'Sports Sellers ES', c:'Zapatillas Trekking' },
      { n:'Hoka Mach 7', p:145.95, op:180.98, b:'Hoka', s:'Sprinter', c:'Zapatillas running' },
      { n:'Merrell Moab Speed 2 Gtx', p:142.95, op:169.99, b:'Merrell', s:'Sprinter', c:'Botas montaña' },
      { n:'adidas Predator Pro Ft Fg', p:139.99, op:169.99, b:'adidas', s:'Sprinter', c:'Botas fútbol tacos' },
      { n:'Hoka Bondi 9', p:138.95, op:184.72, b:'Hoka', s:'Sprinter', c:'Zapatillas running' },
      { n:'Joma Smash', p:137.18, op:0, b:'Joma', s:'Sports Sellers ES', c:'Zapatillas Pádel' },
      { n:'adidas Agravic Speed 2', p:134.99, op:159.99, b:'adidas', s:'Sprinter', c:'Zapatillas running' },
      { n:'La Sportiva Akyra', p:134.99, op:202.65, b:'La Sportiva', s:'Sports Sellers ES', c:'Zapatillas Trekking' },
      { n:'Joma Roland Lady 25', p:131.99, op:0, b:'Joma', s:'JOMA', c:'Zapatillas Tenis' },
      { n:'adidas Ultraboost 5', p:129.99, op:193.61, b:'adidas', s:'Sprinter', c:'Zapatillas running' },
      { n:'adidas Adizero Boston 13', p:124.99, op:159.99, b:'adidas', s:'Sprinter', c:'Zapatillas running' },
      { n:'adidas Soulstride Flow', p:124.99, op:139.99, b:'adidas', s:'Sprinter', c:'Zapatillas running' },
      { n:'adidas Dropset 4 Power', p:119.99, op:129.99, b:'adidas', s:'Sprinter', c:'Zapatillas fitness' },
      { n:'adidas Predator Pro Ft Ag', p:119.99, op:159.99, b:'adidas', s:'adidas ES', c:'Botas Fútbol Tacos' },
      { n:'adidas Terrex Trailmaker 2', p:119.99, op:0, b:'adidas', s:'adidas ES', c:'Zapatillas Trekking' },
      { n:'Anorak adidas', p:119.99, op:0, b:'adidas', s:'adidas ES', c:'Anorak Trekking' },
      { n:'adidas Supernova Rise 2', p:119.66, op:170.53, b:'adidas', s:'adidas ES', c:'Zapatillas Running' },
      { n:'adidas Adizero Adios 9', p:114.99, op:146.28, b:'adidas', s:'Sprinter', c:'Zapatillas running' },
      { n:'adidas Ae 1 Low', p:109.99, op:0, b:'adidas', s:'adidas ES', c:'Zapatillas Baloncesto' },
      { n:'Merrell Moab Speed 2 Gtx', p:108.95, op:274.10, b:'Merrell', s:'Sprinter', c:'Zapatillas montaña' },
      { n:'Merrell Antora 4', p:107.95, op:134.99, b:'Merrell', s:'Sprinter', c:'Zapatillas running' },
      { n:'adidas Ae 2', p:103.98, op:129.99, b:'adidas', s:'adidas ES', c:'Zapatillas Baloncesto' },
      { n:'Mizuno Ultima 17', p:103.95, op:104.99, b:'Mizuno', s:'Sprinter', c:'Zapatillas running' },
      { n:'Joma Point 2204', p:101.15, op:0, b:'Joma', s:'Stateside', c:'Zapatillas Padel' },
      { n:'adidas Harden Volume 9', p:101.10, op:206.10, b:'adidas', s:'Sports Sellers ES', c:'Zapatillas Baloncesto' },
      { n:'Mizuno Fortrush', p:100.95, op:130.06, b:'Mizuno', s:'Sprinter', c:'Zapatillas running' },
      { n:'1ª Camiseta Real Madrid 25/26', p:99.99, op:0, b:'Real Madrid', s:'adidas ES', c:'Camiseta Fútbol' },
      { n:'2ª Camiseta España Mundial 2026', p:99.99, op:126.62, b:'adidas', s:'Sports Sellers ES', c:'Equipación' },
      { n:'3ª Camiseta Arsenal Fc 25/26', p:99.99, op:0, b:'Arsenal Fc', s:'adidas ES', c:'Equipación' },
      { n:'adidas Supernova Glide M', p:99.99, op:129.99, b:'adidas', s:'Sprinter', c:'Zapatillas running' },
      { n:'adidas Terrex Swift R2 Gtx', p:99.99, op:212.69, b:'adidas', s:'Sports Sellers ES', c:'Zapatillas Trekking' },
      { n:'Hoka Rincon 4', p:94.95, op:157.45, b:'Hoka', s:'Sprinter', c:'Zapatillas running' },
      { n:'adidas Barreda Decode Lux', p:89.99, op:0, b:'adidas', s:'Sprinter', c:'Zapatillas casual' },
      { n:'adidas F50 League Fg Mg', p:89.99, op:114.55, b:'adidas', s:'Sprinter', c:'Botas fútbol tacos' },
      { n:'adidas A. Edwards 1', p:89.99, op:106.82, b:'adidas', s:'Sports Sellers ES', c:'Zapatillas Baloncesto' },
      { n:'Babolat Stigma Vita', p:89.85, op:0, b:'Babolat', s:'PadelPROShop', c:'Pala Pádel Mujer' },
      { n:'adidas Terrex Voyager 21', p:86.67, op:103.04, b:'adidas', s:'adidas ES', c:'Zapatillas Trekking' },
      { n:'adidas F50 Elite Fg', p:84.99, op:119.99, b:'adidas', s:'Sprinter', c:'Botas fútbol sala' },
      { n:'adidas Terrex Swift R3', p:84.99, op:210.30, b:'adidas', s:'Sports Sellers ES', c:'Zapatillas Trekking' },
      { n:'adidas Ae 1 Mid', p:82.00, op:0, b:'adidas', s:'ALONSPORT', c:'Zapatillas Pádel' },
      { n:'Columbia Bethany Urban', p:79.99, op:112.62, b:'Columbia', s:'Sports Sellers ES', c:'Zapatillas fitness' },
      { n:'adidas Predator League Fg', p:74.99, op:99.99, b:'adidas', s:'Sprinter', c:'Botas fútbol tacos' }
    ]
  },

  get compFilteredProducts() {
    let list = this.compData.products;
    if (this.compSearch) {
      const q = this.compSearch.toLowerCase();
      list = list.filter(p => p.n.toLowerCase().includes(q) || p.b.toLowerCase().includes(q) || p.s.toLowerCase().includes(q) || p.c.toLowerCase().includes(q));
    }
    if (this.compFilterSeller) list = list.filter(p => p.s === this.compFilterSeller);
    if (this.compFilterCat) list = list.filter(p => p.c.toLowerCase().includes(this.compFilterCat.toLowerCase()));
    return list;
  },
  get compUniqueSellers() { return [...new Set(this.compData.products.map(p => p.s))].sort(); },
  get compUniqueCats() { return [...new Set(this.compData.products.map(p => p.c).filter(Boolean))].sort(); },
};
